services:
  api:
    build: .
    container_name: aurora_api
    ports:
      - "9878:9878"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 9878 --reload
    restart: unless-stopped
